-- Drop existing table if you want to start fresh
-- DROP TABLE IF EXISTS groceries CASCADE;
-- DROP TABLE IF EXISTS shopping_list CASCADE;

-- Main Inventory Table
CREATE TABLE IF NOT EXISTS groceries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  item_name TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'General',
  current_stock INTEGER NOT NULL DEFAULT 0,
  min_stock INTEGER NOT NULL DEFAULT 1,
  unit TEXT DEFAULT 'units', -- e.g., 'liters', 'kg', 'units', 'bottles'
  price NUMERIC DEFAULT 0,
  last_purchased_date DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Shopping List Table
CREATE TABLE IF NOT EXISTS shopping_list (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  grocery_id BIGINT REFERENCES groceries(id) ON DELETE CASCADE,
  item_name TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'General',
  quantity INTEGER NOT NULL DEFAULT 1,
  unit TEXT DEFAULT 'units',
  price NUMERIC DEFAULT 0,
  is_picked BOOLEAN DEFAULT FALSE,
  is_auto_added BOOLEAN DEFAULT FALSE, -- true if added by low stock alert
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE groceries ENABLE ROW LEVEL SECURITY;
ALTER TABLE shopping_list ENABLE ROW LEVEL SECURITY;

-- RLS Policies for groceries
CREATE POLICY "Users can view their own groceries"
  ON groceries FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own groceries"
  ON groceries FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own groceries"
  ON groceries FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own groceries"
  ON groceries FOR DELETE
  USING (auth.uid() = user_id);

-- RLS Policies for shopping_list
CREATE POLICY "Users can view their own shopping list"
  ON shopping_list FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own shopping list items"
  ON shopping_list FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own shopping list items"
  ON shopping_list FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own shopping list items"
  ON shopping_list FOR DELETE
  USING (auth.uid() = user_id);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_groceries_user_id ON groceries(user_id);
CREATE INDEX IF NOT EXISTS idx_groceries_category ON groceries(category);
CREATE INDEX IF NOT EXISTS idx_shopping_list_user_id ON shopping_list(user_id);
CREATE INDEX IF NOT EXISTS idx_shopping_list_grocery_id ON shopping_list(grocery_id);

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = TIMEZONE('utc'::text, NOW());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to update updated_at on groceries
DROP TRIGGER IF EXISTS update_groceries_updated_at ON groceries;
CREATE TRIGGER update_groceries_updated_at
  BEFORE UPDATE ON groceries
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
