-- Neon (Lakebase Postgres) initial schema
-- Ported from Supabase: transactions, assets, liabilities, investments,
-- financial_goals, services, service_history, groceries, shopping_list,
-- category_budget, user_uploads
-- Auth: Neon Auth (Managed Better Auth) via Data API
-- RLS uses auth.user_id() (TEXT sub claim). All user_id columns are TEXT.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Shared updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ================= transactions =================
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  date DATE NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  amount NUMERIC NOT NULL DEFAULT 0,
  category TEXT NOT NULL DEFAULT 'Other',
  ai_category TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_date ON transactions(date DESC);
CREATE INDEX IF NOT EXISTS idx_transactions_category ON transactions(category);

-- ================= assets =================
CREATE TABLE IF NOT EXISTS assets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IS NOT NULL AND length(trim(type)) > 0),
  current_value NUMERIC NOT NULL DEFAULT 0,
  last_updated DATE,
  created_on DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_assets_user_id ON assets(user_id);

-- ================= liabilities =================
CREATE TABLE IF NOT EXISTS liabilities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL,
  name TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'loan',
  principal NUMERIC NOT NULL DEFAULT 0,
  opening_principal NUMERIC,
  current_principal NUMERIC,
  interest_rate_annual NUMERIC NOT NULL DEFAULT 0,
  monthly_emi NUMERIC NOT NULL DEFAULT 0,
  extra_payment_monthly NUMERIC NOT NULL DEFAULT 0,
  start_date DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON COLUMN liabilities.principal IS 'Original loan principal amount. Current balance is calculated from payment history.';
CREATE INDEX IF NOT EXISTS idx_liabilities_user_id ON liabilities(user_id);

-- ================= investments =================
CREATE TABLE IF NOT EXISTS investments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('Stock', 'Mutual Fund', 'Crypto', 'Gold', 'Real Estate', 'Bond', 'ETF', 'Other')),
  invested_amount NUMERIC NOT NULL,
  current_value NUMERIC NOT NULL,
  date DATE NOT NULL,
  notes TEXT,
  quantity NUMERIC,
  symbol VARCHAR(20),
  last_updated TIMESTAMPTZ,
  auto_refresh BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_investments_date ON investments(date DESC);
CREATE INDEX IF NOT EXISTS idx_investments_type ON investments(type);
CREATE INDEX IF NOT EXISTS idx_investments_user_id ON investments(user_id);
CREATE INDEX IF NOT EXISTS idx_investments_symbol ON investments(symbol) WHERE symbol IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_investments_auto_refresh ON investments(auto_refresh) WHERE auto_refresh = TRUE;

-- ================= financial_goals =================
CREATE TABLE IF NOT EXISTS financial_goals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL,
  name TEXT NOT NULL,
  target_amount NUMERIC NOT NULL,
  current_amount NUMERIC DEFAULT 0,
  deadline DATE NOT NULL,
  category TEXT CHECK (category IN ('savings', 'investment', 'debt', 'purchase', 'other')) DEFAULT 'other',
  priority TEXT CHECK (priority IN ('high', 'medium', 'low')) DEFAULT 'medium',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_financial_goals_user_id ON financial_goals(user_id);

-- ================= services =================
CREATE TABLE IF NOT EXISTS services (
  id SERIAL PRIMARY KEY,
  user_id TEXT NOT NULL,
  service_name TEXT NOT NULL,
  service_type TEXT NOT NULL,
  last_service_date DATE,
  next_service_due DATE,
  service_provider TEXT,
  cost NUMERIC,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_services_user_id ON services(user_id);
CREATE INDEX IF NOT EXISTS idx_services_next_due ON services(next_service_due);

-- ================= service_history =================
CREATE TABLE IF NOT EXISTS service_history (
  id SERIAL PRIMARY KEY,
  service_id INTEGER NOT NULL REFERENCES services(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL,
  service_date DATE NOT NULL,
  service_provider TEXT,
  cost NUMERIC,
  notes TEXT,
  odometer_reading INTEGER,
  work_performed TEXT,
  parts_replaced TEXT[],
  next_service_due DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_service_history_service_id ON service_history(service_id);
CREATE INDEX IF NOT EXISTS idx_service_history_user_id ON service_history(user_id);
CREATE INDEX IF NOT EXISTS idx_service_history_service_date ON service_history(service_date DESC);

CREATE OR REPLACE FUNCTION create_service_history_on_update()
RETURNS TRIGGER AS $$
BEGIN
  IF (OLD.last_service_date IS DISTINCT FROM NEW.last_service_date)
     OR (OLD.cost IS DISTINCT FROM NEW.cost) THEN
    INSERT INTO service_history (
      service_id, user_id, service_date, service_provider, cost, notes, next_service_due
    ) VALUES (
      OLD.id, OLD.user_id, OLD.last_service_date, OLD.service_provider, OLD.cost, OLD.notes, OLD.next_service_due
    );
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS service_update_history_trigger ON services;
CREATE TRIGGER service_update_history_trigger
  BEFORE UPDATE ON services
  FOR EACH ROW
  EXECUTE FUNCTION create_service_history_on_update();

CREATE OR REPLACE FUNCTION create_initial_service_history()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO service_history (
    service_id, user_id, service_date, service_provider, cost, notes, next_service_due
  ) VALUES (
    NEW.id, NEW.user_id, NEW.last_service_date, NEW.service_provider, NEW.cost, NEW.notes, NEW.next_service_due
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS service_insert_history_trigger ON services;
CREATE TRIGGER service_insert_history_trigger
  AFTER INSERT ON services
  FOR EACH ROW
  EXECUTE FUNCTION create_initial_service_history();

CREATE OR REPLACE FUNCTION get_service_statistics(p_service_id INTEGER)
RETURNS TABLE (
  total_services BIGINT,
  total_cost NUMERIC,
  average_cost NUMERIC,
  last_service_date DATE,
  average_interval_days INTEGER
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    COUNT(*)::BIGINT AS total_services,
    COALESCE(SUM(cost), 0) AS total_cost,
    COALESCE(AVG(cost), 0) AS average_cost,
    MAX(service_date) AS last_service_date,
    CASE
      WHEN COUNT(*) > 1 THEN
        CAST((MAX(service_date) - MIN(service_date)) / NULLIF(COUNT(*) - 1, 0) AS INTEGER)
      ELSE 0
    END AS average_interval_days
  FROM service_history
  WHERE service_id = p_service_id;
END;
$$ LANGUAGE plpgsql;

-- ================= groceries =================
CREATE TABLE IF NOT EXISTS groceries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  item_name TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'General',
  current_stock INTEGER NOT NULL DEFAULT 0,
  min_stock INTEGER NOT NULL DEFAULT 1,
  unit TEXT DEFAULT 'units',
  price NUMERIC DEFAULT 0,
  last_purchased_date DATE,
  package_size TEXT,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_groceries_user_id ON groceries(user_id);
CREATE INDEX IF NOT EXISTS idx_groceries_category ON groceries(category);

DROP TRIGGER IF EXISTS update_groceries_updated_at ON groceries;
CREATE TRIGGER update_groceries_updated_at
  BEFORE UPDATE ON groceries
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ================= shopping_list =================
CREATE TABLE IF NOT EXISTS shopping_list (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  grocery_id BIGINT REFERENCES groceries(id) ON DELETE CASCADE,
  item_name TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'General',
  quantity INTEGER NOT NULL DEFAULT 1,
  unit TEXT DEFAULT 'units',
  price NUMERIC DEFAULT 0,
  is_picked BOOLEAN DEFAULT FALSE,
  is_auto_added BOOLEAN DEFAULT FALSE,
  package_size TEXT,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_shopping_list_user_id ON shopping_list(user_id);
CREATE INDEX IF NOT EXISTS idx_shopping_list_grocery_id ON shopping_list(grocery_id);

-- ================= category_budget =================
CREATE TABLE IF NOT EXISTS category_budget (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  category TEXT NOT NULL,
  budget NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, category)
);
CREATE INDEX IF NOT EXISTS idx_category_budget_user_id ON category_budget(user_id);

-- ================= user_uploads =================
CREATE TABLE IF NOT EXISTS user_uploads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL UNIQUE,
  last_upload_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_user_uploads_user_id ON user_uploads(user_id);

-- ================= updated_at triggers =================
DROP TRIGGER IF EXISTS update_assets_updated_at ON assets;
CREATE TRIGGER update_assets_updated_at
  BEFORE UPDATE ON assets FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_liabilities_updated_at ON liabilities;
CREATE TRIGGER update_liabilities_updated_at
  BEFORE UPDATE ON liabilities FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_investments_updated_at ON investments;
CREATE TRIGGER update_investments_updated_at
  BEFORE UPDATE ON investments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_services_updated_at ON services;
CREATE TRIGGER update_services_updated_at
  BEFORE UPDATE ON services FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ================= RLS =================
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE liabilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE investments ENABLE ROW LEVEL SECURITY;
ALTER TABLE financial_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE groceries ENABLE ROW LEVEL SECURITY;
ALTER TABLE shopping_list ENABLE ROW LEVEL SECURITY;
ALTER TABLE category_budget ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_uploads ENABLE ROW LEVEL SECURITY;

-- Drop legacy Supabase policies if re-running (names may collide)
DO $$
DECLARE t TEXT;
BEGIN
  FOR t IN SELECT unnest(ARRAY['transactions','assets','liabilities','investments','financial_goals','services','service_history','groceries','shopping_list','category_budget','user_uploads'])
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS "Users can view their own %s" ON %I', t, t);
  END LOOP;
END $$;

-- Canonical Neon Data API policy: owners manage own rows
DROP POLICY IF EXISTS manage_own_rows ON transactions;
CREATE POLICY manage_own_rows ON transactions FOR ALL TO authenticated
  USING (auth.user_id() = user_id) WITH CHECK (auth.user_id() = user_id);

DROP POLICY IF EXISTS manage_own_rows ON assets;
CREATE POLICY manage_own_rows ON assets FOR ALL TO authenticated
  USING (auth.user_id() = user_id) WITH CHECK (auth.user_id() = user_id);

DROP POLICY IF EXISTS manage_own_rows ON liabilities;
CREATE POLICY manage_own_rows ON liabilities FOR ALL TO authenticated
  USING (auth.user_id() = user_id) WITH CHECK (auth.user_id() = user_id);

DROP POLICY IF EXISTS manage_own_rows ON investments;
CREATE POLICY manage_own_rows ON investments FOR ALL TO authenticated
  USING (auth.user_id() = user_id) WITH CHECK (auth.user_id() = user_id);

DROP POLICY IF EXISTS manage_own_rows ON financial_goals;
CREATE POLICY manage_own_rows ON financial_goals FOR ALL TO authenticated
  USING (auth.user_id() = user_id) WITH CHECK (auth.user_id() = user_id);

DROP POLICY IF EXISTS manage_own_rows ON services;
CREATE POLICY manage_own_rows ON services FOR ALL TO authenticated
  USING (auth.user_id() = user_id) WITH CHECK (auth.user_id() = user_id);

DROP POLICY IF EXISTS manage_own_rows ON service_history;
CREATE POLICY manage_own_rows ON service_history FOR ALL TO authenticated
  USING (auth.user_id() = user_id) WITH CHECK (auth.user_id() = user_id);

DROP POLICY IF EXISTS manage_own_rows ON groceries;
CREATE POLICY manage_own_rows ON groceries FOR ALL TO authenticated
  USING (auth.user_id() = user_id) WITH CHECK (auth.user_id() = user_id);

DROP POLICY IF EXISTS manage_own_rows ON shopping_list;
CREATE POLICY manage_own_rows ON shopping_list FOR ALL TO authenticated
  USING (auth.user_id() = user_id) WITH CHECK (auth.user_id() = user_id);

DROP POLICY IF EXISTS manage_own_rows ON category_budget;
CREATE POLICY manage_own_rows ON category_budget FOR ALL TO authenticated
  USING (auth.user_id() = user_id) WITH CHECK (auth.user_id() = user_id);

DROP POLICY IF EXISTS manage_own_rows ON user_uploads;
CREATE POLICY manage_own_rows ON user_uploads FOR ALL TO authenticated
  USING (auth.user_id() = user_id) WITH CHECK (auth.user_id() = user_id);

-- Grants for Data API authenticated role
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO authenticated;
